import { View } from 'react-native'
import { useSettingsStore } from '@/store/settings/store'
import AppBinaryRadioButtonsGroup from '@/components/ui/AppBinaryRadioButtonsGroup'

const isAIModeOptions: [string, string] = ['Artificial Intelligence', 'System']

export default function Settings() {
  const { isAIMode, setSettingsState } = useSettingsStore()

  return (
    <View>
      <AppBinaryRadioButtonsGroup
        label='Questions are generated by'
        options={isAIModeOptions}
        onValueChange={value => setSettingsState({ isAIMode: value })}
        value={isAIMode}
      />
    </View>
  )
}
