import { View } from 'react-native'
import { useSettingsStore } from '@/store/settings/store'
import AppText from '@/components/ui/AppText'
import AppTouchableOpacity from '@/components/ui/AppTouchableOpacity'

export default function Settings() {
  const { isAIMode, setSettingsState } = useSettingsStore()
  const onChangeAIMode = (prop: boolean) => {
    setSettingsState({ isAIMode: prop })
  }
  return (
    <View className='flex-1'>
      <View className='flex flex-col'>
        <AppText className='text-lg font-bold mb-sm'>
          Questions are generated by
        </AppText>
        <View className='flex flex-row'>
          <AppTouchableOpacity
            onPress={() => onChangeAIMode(true)}
            className={`${isAIMode ? 'bg-secondary border-primary' : ' '}`}
          >
            <AppText
              className={`text-center ${isAIMode ? 'text-primary' : ''}`}
            >
              Artificial Intelligence {isAIMode ? '✓' : ''}
            </AppText>
          </AppTouchableOpacity>
          <AppTouchableOpacity
            onPress={() => onChangeAIMode(false)}
            className={`ml-sm ${
              !isAIMode ? 'bg-secondary text-primary border-secondary' : ' '
            }`}
          >
            <AppText className={`${!isAIMode ? 'text-primary' : ''}`}>
              System {!isAIMode ? '✓' : ''}
            </AppText>
          </AppTouchableOpacity>
        </View>
      </View>
    </View>
  )
}
