import { useState } from 'react'
import { View } from 'react-native'
import { useSettingsStore } from '@/store/settings/store'
import { SettingsState } from '@/store/settings/types'
import AppBinaryRadioButtonsGroup from '@/components/ui/AppBinaryRadioButtonsGroup'

const AIModeTemplate = {
  label: 'Questions are generated by',
  options: ['Artificial Intelligence', 'System'],
}

export default function AIMode() {
  const { setSettingsState, language, aiMode, timer } = useSettingsStore()
  const [tempSettings, setTempSettings] = useState<SettingsState>({
    language,
    aiMode,
    timer,
  })

  const setPartialSettingsState = (partialState: Partial<SettingsState>) => {
    setTempSettings(prev => ({ ...prev, ...partialState }))
  }

  return (
    <View>
      <AppBinaryRadioButtonsGroup
        label={AIModeTemplate.label}
        options={AIModeTemplate.options}
        onValueChange={value =>
          setPartialSettingsState({ aiMode: { ...aiMode, enabled: value } })
        }
        value={tempSettings.aiMode.enabled}
      />
    </View>
  )
}
